

ALTER TABLE CUSTOMER ADD CONSTRAINT UK_PHONE UNIQUE(PHONE);

ALTER TABLE ORDERS ADD CONSTRAINT UK_SHIPPING_DATE UNIQUE(SHIPPING_DATE);

ALTER TABLE PRODUCT ADD CONSTRAINT UK_PRODUCT_NAME UNIQUE(PRODUCT_NAME);

ALTER TABLE PRODUCT ADD CONSTRAINT CK_QUANTITY CHECK(QUANTITY>=1);
